<?php namespace JF;
/**

Copyright 2017 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-53436f
Date:    2017-03-08 15:34:20
Version: v1.2
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-53436f",
    "email": {
        "to": "",
        "cc": "",
        "bcc": "",
        "subject": "",
        "template": ""
    },
    "admin": {
        "users": "admin:bb735",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": false,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "Fecha:",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "date": {
                    "format": "dd\/mm\/yyyy"
                }
            },
            "id": "f4",
            "cid": "c26"
        },
        {
            "label": "Nombre del profesor: ",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "hidden": false,
                "validators": {
                    "required": {
                        "enabled": true
                    },
                    "alphanumeric": {
                        "enabled": false
                    },
                    "min": {
                        "enabled": false,
                        "val": "0"
                    },
                    "max": {
                        "enabled": false,
                        "val": "0"
                    },
                    "minlength": {
                        "enabled": true,
                        "val": "7",
                        "msg": "Introduzca almenos 7 caracteres"
                    },
                    "maxlength": {
                        "enabled": true,
                        "val": "20",
                        "msg": "No introduza m\u00e1s de 20 caracteres"
                    },
                    "equalto": {
                        "enabled": false
                    },
                    "pattern": {
                        "enabled": true,
                        "msg": "F\u00f3rmato inv\u00e1lido",
                        "val": "[\u00f1\u00e1\u00e9\u00ed\u00f3\u00faA-Za-z]"
                    }
                },
                "mask": {
                    "pattern": ""
                }
            },
            "id": "f5",
            "cid": "c18",
            "labelHide": false
        },
        {
            "label": "Materia y c\u00f3digo: ",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "alphanumeric": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "mask": {
                    "pattern": "A"
                }
            },
            "id": "f7",
            "cid": "c28"
        },
        {
            "label": "Secci\u00f3n: ",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f8",
            "cid": "c33"
        },
        {
            "label": "1) comunica los temas de manera comprensible",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f10",
            "cid": "c36",
            "labelHide": false
        },
        {
            "label": "2) explica en detalle los objetivos de la materia",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c33",
            "labelHide": false,
            "id": "f11"
        },
        {
            "label": "3) enriquese las exposisiones con ejemplos de interes",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c40",
            "labelHide": false,
            "id": "f12"
        },
        {
            "label": "4) relaciona sistem\u00e1ticamente los objetivos con los objetivos de la asignatura",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c46",
            "labelHide": false,
            "id": "f13"
        },
        {
            "label": "5) ofrece materiales que propician el aprendizaje",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c52",
            "labelHide": false,
            "id": "f14"
        },
        {
            "label": "6) aclara las dudas que se presentan a lo largo del curso",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c58",
            "labelHide": false,
            "id": "f15"
        },
        {
            "label": "7) establece y comunica previamente los planes de evaluaci\u00f3n",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c64",
            "labelHide": false,
            "id": "f16"
        },
        {
            "label": "8) brinda oportunamente retroalimentaci\u00f3n sobre los resultados de las evaluaciones",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c70",
            "labelHide": false,
            "id": "f17"
        },
        {
            "label": "9) conduce la interacci\u00f3n grupal y estimula la argumentaci\u00f3n en los integrantes del grupo",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c76",
            "labelHide": false,
            "id": "f18"
        },
        {
            "label": "10) incentiva la b\u00fasqueda de informaci\u00f3n complementaria para el curso",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c82",
            "labelHide": false,
            "id": "f19"
        },
        {
            "label": "11) mantiene en esta asignatura un balance entre diferentes actividades: discuiones te\u00f3ricas, sesiones pr\u00e1cticas, aplicaciones diversas y relacionadas con la asignatura",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c88",
            "labelHide": false,
            "id": "f20"
        },
        {
            "label": "12) propicia la responsabilidad y la modela a su conducta",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "cid": "c94",
            "labelHide": false,
            "id": "f21"
        },
        {
            "label": "13) En general, la calidad doncente del profesor es:",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                },
                "description": "Bajo ------------ Alto"
            },
            "cid": "c103",
            "labelHide": false,
            "id": "f22"
        },
        {
            "label": "14) Su disposici\u00f3n a tomar otro curso con este profesor es:",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                },
                "description": "Bajo ------------ Alto"
            },
            "cid": "c109",
            "labelHide": false,
            "id": "f23"
        },
        {
            "label": "15) Su aprovechamiento de esta materia como estudiante est\u00e1 siendo:",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                },
                "description": "Bajo ------------ Alto"
            },
            "cid": "c115",
            "labelHide": false,
            "id": "f24"
        },
        {
            "label": "16) Su dedicaci\u00f3n y esfuerzo como estudiante en este curso est\u00e1 siendo:",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                },
                "description": "Bajo ------------ Alto"
            },
            "cid": "c121",
            "labelHide": false,
            "id": "f25"
        },
        {
            "label": "17) El texto y la bibliograf\u00eda sugerida es adecuada, \u00fatil:",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": true
                    },
                    {
                        "label": "2",
                        "checked": true
                    },
                    {
                        "label": "3",
                        "checked": true
                    },
                    {
                        "label": "4",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "validators": {
                    "min": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "inline"
                },
                "description": "Bajo ------------ Alto"
            },
            "cid": "c131",
            "labelHide": false,
            "id": "f26"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "Enviar",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ]
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class