<?php namespace JF;
/**

Copyright 2017 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-5d9db0
Date:    2017-03-09 11:47:04
Version: v1.2
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-5d9db0",
    "email": {
        "to": "ramonjba@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "encuestik",
        "template": ""
    },
    "admin": {
        "users": "admin:edd2f",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": " Muestra disposici\u00f3n para entender y satisfacer necesidades de la dependencia ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "hidden": false,
                "placeholder": ""
            },
            "id": "f5",
            "cid": "c31"
        },
        {
            "label": " Practica y promueve la honestidad, el respeto, la excelencia y la responsabilidad ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                }
            },
            "cid": "c36",
            "id": "f6"
        },
        {
            "label": " Conoce, da a conocer y respeta las normas y reglamentos ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                }
            },
            "cid": "c42",
            "id": "f7"
        },
        {
            "label": "Respeta los compromisos y las normas establecidas en los grupos o equipos de trabajo ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                }
            },
            "cid": "c49",
            "id": "f8"
        },
        {
            "label": " Participa en Comisiones o Asociaciones, institucionales o de la dependencia ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                }
            },
            "cid": "c56",
            "id": "f9"
        },
        {
            "label": "Cuida su ambiente de trabajo",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                }
            },
            "cid": "c63",
            "id": "f10"
        },
        {
            "label": "Cuida su aspecto personal",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                }
            },
            "cid": "c70",
            "id": "f11"
        },
        {
            "label": "  Acepta el proceso de evaluaci\u00f3n como un medio para identificar las oportunidades de mejora ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                }
            },
            "cid": "c77",
            "id": "f12"
        },
        {
            "label": "  Representa a la Universidad con sentido de pertenencia ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                }
            },
            "cid": "c84",
            "id": "f13"
        },
        {
            "label": " Internaliza con sentido de pertenencia pol\u00edticas y objetivos de la instituci\u00f3n ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c91",
            "id": "f14"
        },
        {
            "label": " Toma decisiones oportunas",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c53",
            "id": "f15"
        },
        {
            "label": "  Demuestra habilidad para expresarse en forma oral y escrita",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c60",
            "id": "f16"
        },
        {
            "label": "   Se maneja con ecuanimidad, prudencia, cortes\u00eda y discreci\u00f3n en situaciones de conflicto ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c63",
            "id": "f17"
        },
        {
            "label": " Demuestra capacidad para verificar la congruencia entre lo que se dice y lo que se hace ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c70",
            "id": "f18"
        },
        {
            "label": " Es oportuno en sus intervenciones",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c77",
            "id": "f19"
        },
        {
            "label": " Manifiesta y demuestra capacidad de negociaci\u00f3n",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c84",
            "id": "f20"
        },
        {
            "label": " Se comunica de manera cort\u00e9s y respetuosa con secretarias, colegas, supervisados y alumnos",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c91",
            "id": "f21"
        },
        {
            "label": " Es discreto en la soluci\u00f3n de conflictos",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c98",
            "id": "f22"
        },
        {
            "label": " En situaciones de conflicto respeta los canales de autoridad",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c105",
            "id": "f23"
        },
        {
            "label": " Asiste a las reuniones de equipo y est\u00e1 dispuesto a ofrecer conocimiento, informaci\u00f3n y experticia para el logro de objetivos comunes.",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c112",
            "id": "f24"
        },
        {
            "label": " Comparte con colegas sus experiencias docentes",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c119",
            "id": "f25"
        },
        {
            "label": " Aporta conocimientos valiosos sobre la materia que dicta, a trav\u00e9s de la coordinaci\u00f3n de la misma",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c126",
            "id": "f26"
        },
        {
            "label": "Es eficiente en la planificaci\u00f3n de tareas o actividades relacionadas con su equipo de trabajo",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c133",
            "id": "f27"
        },
        {
            "label": " Es colaborador, conciliador y sabe escuchar",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c140",
            "id": "f28"
        },
        {
            "label": "Evidencia inter\u00e9s por lograr acuerdos y consensos con el grupo. ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c147",
            "id": "f29"
        },
        {
            "label": " Participa como jurado en trabajos y\/o tesis de grado. ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c154",
            "id": "f30"
        },
        {
            "label": " Muestra disposici\u00f3n a actuar como tutor en trabajos y\/o tesis de grado. ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c161",
            "id": "f31"
        },
        {
            "label": " Conoce la materia a profundidad",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c168",
            "id": "f32"
        },
        {
            "label": " Analiza con el grupo de estudiantes, al inicio del curso, el programa de la materia, haciendo \u00e9nfasis en los objetivos, contenidos, actividades y formas de evaluaci\u00f3n del mismo.",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c175",
            "id": "f33"
        },
        {
            "label": " Expone los conceptos con claridad y precisi\u00f3n y promueve que comprendan el por qu\u00e9 de las cosas ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c182",
            "id": "f34"
        },
        {
            "label": "Promueve el pensamiento cr\u00edtico y utiliza t\u00e9cnicas que favorecen el debate, la discusi\u00f3n y las propuestas de soluci\u00f3n ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c189",
            "id": "f35"
        },
        {
            "label": "  Encarga trabajos que desarrollan la capacidad de identificar y solucionar problemas",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c196",
            "id": "f36"
        },
        {
            "label": " Se mantiene activo en el \u00e1rea de su competencia a nivel te\u00f3rico y pr\u00e1ctico, suministrando informaci\u00f3n vigente a sus alumnos",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c203",
            "id": "f37"
        },
        {
            "label": "Intercambia, expone o exhibe ideas novedosas sobre su materia",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c210",
            "id": "f38"
        },
        {
            "label": " Participa en programas de actualizaci\u00f3n de la Unimet",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c217",
            "id": "f39"
        },
        {
            "label": " Participa en programas de investigaci\u00f3n de la Unimet",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c224",
            "id": "f40"
        },
        {
            "label": " Participa en otros programas de actualizaci\u00f3n profesional, acordes con las metas de la dependencia o de la Universidad ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c231",
            "id": "f41"
        },
        {
            "label": "Organiza y dicta alg\u00fan seminario o taller dentro de su dependencia o a nivel institucional ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c238",
            "id": "f42"
        },
        {
            "label": " Dise\u00f1a alg\u00fan curso o parte de uno, integrando actividades de aprendizaje que requieren el uso de la tecnolog\u00eda ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c245",
            "id": "f43"
        },
        {
            "label": " Muestra apertura al di\u00e1logo y a formas de pensar diferentes a la suya ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c252",
            "id": "f44"
        },
        {
            "label": " Es exigente consigo mismo",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c259",
            "id": "f45"
        },
        {
            "label": " Demuestra aceptar observaciones externas, buscando siempre optimizar su rol",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c266",
            "id": "f46"
        },
        {
            "label": "  Muestra inter\u00e9s y satisfacci\u00f3n en su trabajo",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c273",
            "id": "f47"
        },
        {
            "label": " Promueve actividades innovadoras y de cambio para la dependencia, buscando siempre las oportunidades de mejora ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c280",
            "id": "f48"
        },
        {
            "label": " Es exigente en el logro de sus objetivos ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c287",
            "id": "f49"
        },
        {
            "label": " Asiste a todas sus sesiones, cumple con el tiempo reglamentario de clase ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c294",
            "id": "f50"
        },
        {
            "label": " Evidencia compromiso con estudiantes y colegas",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c301",
            "id": "f51"
        },
        {
            "label": " Evidencia compromiso con la administraci\u00f3n del curso cumpliendo con el programa establecido para la materia. ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c308",
            "id": "f52"
        },
        {
            "label": "Entrega puntualmente las actas, informes, encuestas, y recaudos solicitados por sus superiores o coordinadores. ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c315",
            "id": "f53"
        },
        {
            "label": " Es puntual en todas las actividades de clase, reuniones, etc",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c322",
            "id": "f54"
        },
        {
            "label": " Est\u00e1 disponible en el per\u00edodo intersemestral",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true,
                        "val": "1"
                    },
                    "max": {
                        "enabled": true,
                        "val": "5"
                    }
                },
                "addon": {
                    "rightText": ""
                },
                "placeholder": ""
            },
            "cid": "c329",
            "id": "f55"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ]
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class