'use strict';
module.exports = function(sequelize, DataTypes) {
  var pruebaTipoA = sequelize.define('pruebaTipoA', {
    fecha: DataTypes.STRING,
    nombreP: DataTypes.STRING,
    codigoM: DataTypes.STRING,
    seccion: DataTypes.STRING,
    o1: DataTypes.STRING,
    o2: DataTypes.STRING,
    o3: DataTypes.STRING,
    o4: DataTypes.STRING,
    o5: DataTypes.STRING,
    o6: DataTypes.STRING,
    o7: DataTypes.STRING,
    o8: DataTypes.STRING,
    o9: DataTypes.STRING,
    o10: DataTypes.STRING,
    i1: DataTypes.STRING,
    i2: DataTypes.STRING,
    i3: DataTypes.STRING,
    i4: DataTypes.STRING,
    i5: DataTypes.STRING,
    i6: DataTypes.STRING,
    i7: DataTypes.STRING,
    i8: DataTypes.STRING,
    i9: DataTypes.STRING,
    
    f24: DataTypes.STRING,
    f25: DataTypes.STRING,
    f26: DataTypes.STRING,
    f27: DataTypes.STRING,
    f28: DataTypes.STRING,
    f29: DataTypes.STRING,
    f30: DataTypes.STRING,
    f31: DataTypes.STRING,
    f32: DataTypes.STRING,
    f33: DataTypes.STRING,
    f34: DataTypes.STRING,
    f35: DataTypes.STRING,
    f36: DataTypes.STRING,
    f37: DataTypes.STRING,
    f38: DataTypes.STRING,
    f39: DataTypes.STRING,
    f40: DataTypes.STRING,
    f41: DataTypes.STRING,
    f42: DataTypes.STRING,
    f43: DataTypes.STRING,
    f44: DataTypes.STRING,
    f45: DataTypes.STRING,
    f46: DataTypes.STRING,
    f47: DataTypes.STRING,
    f48: DataTypes.STRING,
    f49: DataTypes.STRING,
    f50: DataTypes.STRING,
    f51: DataTypes.STRING,
    f52: DataTypes.STRING,
    f53: DataTypes.STRING,
    f54: DataTypes.STRING,
    f55: DataTypes.STRING,
    valor: DataTypes.STRING,
    valor2: DataTypes.STRING,
    valor3: DataTypes.STRING,
    valor4: DataTypes.STRING,
    valor5: DataTypes.STRING,
    valor6: DataTypes.STRING,
    valor7: DataTypes.STRING,
    valor8: DataTypes.STRING,
    valort: DataTypes.STRING,
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });
  return pruebaTipoA;
};